#!/bin/sh
#
# Pull down stunnel source and compile it. Stupid simple.
# Famos last words...
#
wget --version > /dev/null 2>&1
if [ $? -ne 0 ]
then
   echo "Requires WGET to pull down the file.  Sorry."
   exit 1
fi
wget ftp://ftp.stunnel.org/stunnel/stunnel-*.tar.gz
gunzip -cd stunnel*.gz|tar -xvf -
rm *gz
cd stunnel-*
./configure
gmake --version > /dev/null 2>&1
if [ $? -eq 0 ]
then
	gmake
else
	make
fi
if [ ! -f src/stunnel ]
then
   echo "Problem compiling.  Sorry."
fi
ln -fs `pwd`/src/stunnel ../../stunnel
echo "Done!"
